site:
  title: "Emanuelle Oliveira"
  description: "Bem vindo a minha timeline pessoal"
personal:
  name: "Emanuelle Oliveira"
  avatar: "https://github.com/Emanuelle-Oliveira.png"
  socialNetworks:
    youtube: "https://youtube.com"
    github: "https://github.com/Emanuelle-Oliveira"
    linkedin: "https://www.linkedin.com/in/emanuelle-trindade-oliveira-24198a224/"